Django_practice1/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from Django_practice1 import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^address/', include('address.urls', namespace='address')),
    path('admin/', admin.site.urls),
]

address/urls.py
from django.conf.urls import url
from . import views

app_name = 'address'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^address/$', views.AddressListView.as_view(), name='address_list'),
    url(r'^address/(?P<pk>\d+)/$', views.AddressDetailView.as_view(), name='address_detail')
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name='index'),

    url(r'^book/$', views.BookList.as_view(), name='book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name='publisher_list'),

    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetail.as_view(), name='publisher_detail'),
    url(r'^about', views.BookListView.as_view())
]

address/models.py
from django.db import models

# Create your models here.


class Address(models.Model):
    name = models.CharField(max_length=100, default='김땡땡')
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=100, default='한밭대학교')

    def __str__(self):
        return self.name

address/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from address.models import Address


# Create your views here.
class IndexView(TemplateView):
    template_name = 'address/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = ['Address']
        return context


class AddressListView(ListView):
    model = Address


class AddressDetailView(DetailView):
    model = Address

address/templates/address/address_detail.html
{% extends "base_address.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>phone Number: {{ object.phone }}</p>
<li>Address: {{ object.address }}</li>
    <li>Email: {{ object.email }}</li>
{% endblock content %}

address/templates/address/address_list.html
{% extends "base_address.html" %}

{% block content %}
    <h2>Address List</h2>
    <ul>
        {% for address in object_list %}
            <li><a href="{% url 'address:address_detail' address.id %}">{{ address.name }}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}

address/templates/address/index.html
{% extends "base_address.html" %}

{% block content %}
    <h2>Address Management System</h2>
    <ul>
        {% for modelname in object_list %}
{% with "address:"|add:modelname|lower|add:"_list" as urlvar %}
        <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
{% endwith %}
        {% endfor %}
    </ul>

{% endblock %}