Django_practice1/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from Django_practice1 import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^address/', include('address.urls', namespace='address')),
    path('admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name='index'),

    url(r'^book/$', views.BookList.as_view(), name='book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name='publisher_list'),

    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetail.as_view(), name='publisher_detail'),
    url(r'^about', views.BookListView.as_view())
]

books/models.py
from django.db import models

# Create your models here.


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self): # __str__ on Python 3
        return self.title


class Author(models.Model):
    salutation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

books/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher
from django.http import HttpResponse
import logging
logger = logging.getLogger(__name__)


#-- TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super(BooksModelView, self).get_context_data(**kwargs)
        context['object_list'] = ['Book', 'Author', 'Publisher']
        return context


#-- ListView
class BookList(ListView):
    model = Book

    def get_queryset(self):
        logger.debug("sss")
        last_book = super().get_queryset().latest('publication_date')
        logger.debug(last_book.publication_date.strftime('%a, %d %b %Y %H:%M:%S GMT'))
        return super().get_queryset()


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


#-- DetailView
class BookDetail(DetailView):
    model = Book


class AuthorDetail(DetailView):
    model = Author


class PublisherDetail(DetailView):
    model = Publisher


class BookListView(ListView):
    model = Book

    def head(self, *args, **kwargs):
        last_book = self.get_queryset().latest('publication_date')
        response = HttpResponse('')
        response['Last-Modified'] = last_book.publication_date.strftime('%a, %d %b %Y %H:%M:%S GMT')
        return response

books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address: {{ object.address }}</li>
{% endblock content %}

books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.title }}</h1>
<br />
<li>Authors:
{% for author in object.authors.all %}
    {{ author }}
    {% if not forloop.last %},{% else %}{% endif %}
{% endfor %}
</li>
<li>Publisher: {{ object.publisher }}</li>
<li>Publication date: {{ object.publication_date }}</li>
{% endblock content %}

books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content%}

books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in object_list %}
{% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
        <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
{% endwith %}
        {% endfor %}
    </ul>

{% endblock %}

books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address: {{ object.address }}</li>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">
                {{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}